### ISSUE TITLE
为啥3月8日宣布的开源，但是代码提交的最后日期是四个月前呢

### ISSUE THREAD

**Issue by zhang7249** [Tencent/TencentKona-11#1]
支持国产，国产牛逼
！！！！！

**Comment by shiyuexw** [comment]
Tencent Kona JDK11 和腾讯内部使用的Kona JDK11 同源，生产版本即开源版本。在生产版本在腾讯业务充分验证后，再进行开源；同时开源需要一定的准备工作。综合这两方面，开源版本相比于生产版本会有所延迟。
我们会进行定期发布，把在腾讯生产验证过的技术，及时对外开源。
