### ISSUE TITLE
Pushed to the SDKMan?

### ISSUE THREAD

**Issue by tonycody** [Tencent/TencentKona-11#18]
https://sdkman.io/jdks#albba

Dragonwell has been pushed to the sdkman JDK list,When is Kona?

**Comment by felixxfyang** [comment]
Excuse me for late response, we will evaluate and feedback ASAP. Thanks a lot for your kind suggestion.

**Comment by johnshajiang** [comment]
@tonycody 
SDKMAN just supported Kona JDK.

```
% sdk list java | grep kona
Tencent       |     | 17.0.7       | kona    |            | 17.0.7-kona
              |     | 11.0.19      | kona    |            | 11.0.19-kona
              |     | 8.0.372      | kona    |            | 8.0.372-kona
```
