### ISSUE TITLE
Vector API document

### ISSUE THREAD

**Issue by huangxiaopingRD** [Tencent/TencentKona-11#19]
Can vector api provide a demo document, because many class names and methods have changed in the process of incubating vector api in subsequent versions of open jdk, if kona jdk can have a document to better understand the vectorization functions it provides.

**Comment by DamonFool** [comment]
> Can vector api provide a demo document, because many class names and methods have changed in the process of incubating vector api in subsequent versions of open jdk, if kona jdk can have a document to better understand the vectorization functions it provides.

Sorry for the late.

Actually, you can find the Kona11 vector api doc here https://github.com/Tencent/TencentKona-11/releases/download/kona11.0.8-vector-api/TencentKona11.0.8-internal_jdk_vector-api_linux_javadoc.tar.gz .
Thanks.
