### ISSUE TITLE
不知有没有可以主动触发把Java Heap内存释放归还给系统内存的功能

### ISSUE THREAD

**Issue by jiangguilong2000** [Tencent/TencentKona-11#2]
最近项目打算用kona,由于我们的产品是游戏产品，有个特性就是在导量的第一两天游戏服会导入很多玩家，PCU很高导致临时撑大堆内存，但2天后，80%+的玩家可能会流失，这样，每个游戏进程就冗余了很多堆内存没法释放，而服务器起码要1周+ 以上才停机维护。同时由于内存被占用，不能在虚拟机上另开新区，而且因为被内存占用被撑大，经常会被系统告警，系统内存不足。

以前用过AliJDK，他们提供了一个功能：**将闲置的Java Heap归还物理内存，提高内存的使用效率，提高应用部署密度**
就是使用命令行选项-XX:+DeallocateHeapPages，可以把不使用的HEAP归还给物理内存。这样，我们在系统内存不足的时候，会被动触发FULLGC，让进程腾出闲置内存，或者每天凌晨主动释放进程的闲置内存给系统。大大节省了我们的服务器资源成本，也不会再忍受内存不足的告警起码一个星期。：）
不知kona有没有这个特性，没有的话，希望支持，谢谢！

**Comment by wattsun110** [comment]
谢谢这位同学的关注。
1. TencentKona-11暂时还没有这个功能，后续会考虑加上去。

2. 目前在开源的[tencentKona-8](https://github.com/Tencent/TencentKona-8)里面已经针对ps，cms和g1实现了这个功能，但是默认关闭，需要加参数开启，使用方法和参数说明如下：
    1.1 在启动参数里添加-XX:+FreeHeapPhysicalMemory，针对PS，CMS和G1算法，则在触发FullGC（G1算法除了FullGC，还包括concurrent cycle）后，JVM会释放没有对象的old区的后半部分虚拟地址空间对应的物理内存（G1算法则会有选择的释放部分没有任何对象的region对应的物理内存）。这个参数开启的情况下，还可以分别配合以下两个参数来实现根据load（1.2所描述）和定时强制触发（1.3所描述）FullGC的功能来实现物理内存回收。

1.2 在FreeHeapPhysicalMemory开启的情况下，如果在启动参数里面指定 -XX:PeriodicGCInterval=x（单位是ms）的话，则JVM会每隔5min，自动判断当前进程的load，如果连续3次低于该进程load的P99的话，则会自动触发一次FullGC进行物理内存回收，PeriodicGCInterval时间间隔内最多只会触发一次FullGC，默认PeriodicGCInterval=0，表示这个功能默认是关闭的，此外，load的衡量方式是ygc的频率，也就是说ygc的频率足够低的话，而且距离上一次Ful GC的时间间隔超过PeriodicGCInterval的话，jvm会自动触发Full GC来回收物理内存。
 
1.3 在FreeHeapPhysicalMemory参数开启的情况下，kona jdk8里面还添加了一个定时触发FullGC的功能，如果设置ForcePeriodicGCInterval=x（单位为ms），那么每隔x ms，就会触发一次FullGC。

综上所述，如果只是需要FullGC后回收物理内存功能，那么在进程的启动参数添加-XX:+FreeHeapPhysicalMemory即可，如果需要在系统load的低的时候自动触发FullGC回收物理内存，那么需要再配置下PeriodicGCInterval。定期触发FullGC来回收物理内存回收，这个是针对大数据离线任务设计的功能，游戏场景不一定适合，建议不要配置，直接默认关闭即可。

**Comment by jiangguilong2000** [comment]
不错，支持做的更加彻底，自己FULLGC的定时脚本都免了

**Comment by jdklog** [comment]
其实不能理解为什么这样一个功能,openjdk却不考虑呢?
不知道是出于什么样的考虑,才会忽略这样一个功能.

既然能申请堆外内存,就不让释放.

是不是openjdk最开始没有想过开放堆外内存的功能呢?

毕竟这个功能使用很复杂.

unsafe.

**Comment by jdklog** [comment]
其实不能理解为什么这样一个功能,openjdk却不考虑呢?
不知道是出于什么样的考虑,才会忽略这样一个功能.

既然能申请堆外内存,就不让释放.

是不是openjdk最开始没有想过开放堆外内存的功能呢?

毕竟这个功能使用很复杂.

unsafe.

**Comment by shiyuexw** [comment]
Tencent Kona JDK 11.0.14已支持该特性，通过-XX:+FreeHeapPhysicalMemory 打开这个特性

**Comment by jiangguilong2000** [comment]
> ForcePeriodicGCInterval

试了下ForcePeriodicGCInterval无效，-XX:+FreeHeapPhysicalMemory  -XX:ForcePeriodicGCInterval=60000，预期是一分钟一次FULLGC 但发现没有触发，从启动时的FGC 3次一直没有增加上去，
![image](https://user-images.githubusercontent.com/5009933/209060802-505f6cad-e0e6-42b5-b667-07bb89662701.png)
