### ISSUE TITLE
如何基于该版本jdk实现springboot应用的APPCDS

### ISSUE THREAD

**Issue by xieyang1994** [Tencent/TencentKona-11#21]
我关注到腾讯开源的jdk11，针对APPCDS有一些改进。
原生的JDK11的APPCDS特性针对SpringBoot框架的嵌套Jar包不适用，想问一下腾讯的jdk11的APPCDS特性针对Springboot有什么改善吗，能否说下该如何使用？

**Comment by shiyuexw** [comment]
KonaJDK11 支持JDK6编译生成的jar包，可以使更多的class可以通过AppCDS加载
具体的使用方式和社区版本的AppCDS一致，用法参考https://openjdk.org/jeps/310

springboot的嵌套Jar包是指war包吧，建议将war包解开后，通过-cp指定
