### ISSUE TITLE
JEP346-立即从 G1 返回未使用的已提交内存功能咨询

### ISSUE THREAD

**Issue by czy006** [Tencent/TencentKona-11#30]
https://openjdk.org/jeps/346 

想问问G1特性在腾讯jdk11是否有支持此特性，或者有相似的功能可以开启

**Comment by shiyuexw** [comment]
该特性已经在KonaJDK11

**Comment by czy006** [comment]
@shiyuexw 谢谢解答，目前g1移植是jdk17最高生产可用的版本吗？如果使用 是否按照openjdk17 g1 的相关配置 即可享受此特性

**Comment by shiyuexw** [comment]
没有完全移植，我们通常会根据生产的需要选择特性移植。
