### ISSUE TITLE
请问下jdk都是gpl，我要是用着商用得话，需要把我得jar/war都给客户不

### ISSUE THREAD

**Issue by xx-zhang** [Tencent/TencentKona-11#32]
rt; 协议问题

**Comment by shiyuexw** [comment]
Tencent Kona JDK11 is licensed under the GNU General Public License Version 2 **with "CLASSPATH" EXCEPTION**. 
关于 GNU General Public License, version 2, with the Classpath Exception的解释见：https://openjdk.org/legal/gplv2+ce.html
