### ISSUE TITLE
无法开启ZGC?

### ISSUE THREAD

**Issue by Clownsw** [Tencent/TencentKona-11#35]
**-Xms256M -XX:+CompactStrings -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -XX:+FreeHeapPhysicalMemory**
Option -XX:+UseZGC not supported

**Comment by shiyuexw** [comment]
麻烦提供下使用的KonaJDK11版本

**Comment by Clownsw** [comment]
> 麻烦提供下使用的KonaJDK11版本

Tencent Kona JDK 11.0.17-GA

**Comment by shiyuexw** [comment]
java  -Xms256M -XX:+CompactStrings -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -XX:+FreeHeapPhysicalMemory -version 报什么错误？

**Comment by Clownsw** [comment]
> java -Xms256M -XX:+CompactStrings -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -XX:+FreeHeapPhysicalMemory -version 报什么错误？

D:\TencentKona-11.0.17.b1\bin>java -Xms256M -XX:+CompactStrings -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -XX:+FreeHeapPhysicalMemory -version
Error occurred during initialization of VM
Option -XX:+UseZGC not supported
