### ISSUE TITLE
Is there a windows/mac build?

### ISSUE THREAD

**Issue by richwxd** [Tencent/TencentKona-11#4]
If there is no windows/mac build for developers, it is inconvenient because we usually use windows/mac as a developer environment.

**Comment by shiyuexw** [comment]
目前还没有提供windows/Mac的build，现阶段主要针对JDK的服务能力进行优化，仅提供linux下的版本。windows/mac下的开发版本已经列入规划中。
Tencent Kona JDK与openJDK完全兼容，可以在开发环境下使用openjdk，在生产环境使用Tencent Kona JDK。

**Comment by shiyuexw** [comment]
11.0.13 版本已提供windows/Macos x86的build供试用。
