### ISSUE TITLE
keytool不支持sm2算法吗？

### ISSUE THREAD

**Issue by shenxuebing** [Tencent/TencentKona-11#41]

**Comment by johnshajiang** [comment]
@xuebing1995 
Kona JDK目前没有支持国密算法，但我们提供了独立的Java组件[TencentKonaSMSuite]，支持了国密的密码学算法，包括SM2，SM3和SM4，也支持了国密安全通信协议，包括国密SSL/TLCP和TLS 1.3（RFC 8998）。
特别地，TencentKonaSMSuite提供了[KeyTool]工具类，它的功能与JDK的keytool工具相同，但针对证书和PKCS#12密钥库(keystore)支持了国密算法。
另外，它还额外提供了[KeyStoreTool]工具类，可以将已有的证书和私钥导入到密钥库中，也能够支持使用的国密算法的证书和私私钥。
具体用法，可以参考[测试程序]。

[TencentKonaSMSuite]:
<https://github.com/Tencent/TencentKonaSMSuite>

[KeyTool]:
<https://github.com/Tencent/TencentKonaSMSuite/blob/master/kona-pkix/src/main/java/com/tencent/kona/pkix/tool/KeyTool.java>

[KeyStoreTool]:
<https://github.com/Tencent/TencentKonaSMSuite/blob/master/kona-pkix/src/main/java/com/tencent/kona/pkix/tool/KeyStoreTool.java>

[测试程序]：
<https://github.com/Tencent/TencentKonaSMSuite/tree/master/kona-pkix/src/test/java/com/tencent/kona/pkix/tool>

**Comment by xuebing1995** [comment]
感谢，那这个组件有集成到tomcat中使用国密SSL/TLCP和TLS 1.3（RFC 8998）的Demo或者示例吗？

**Comment by johnshajiang** [comment]
@shenxuebing 
TencentKonaSMSuite中有一些[Demo]，其中包括有与Jetty和Netty的集成，但还没有Tomcat的例子。
但基于相同的原理，就是要让Tomcat使用上TencentKonaSMSuite/KonsSSL的[SSLContext]实现。

如有更多关于TencentKonaSMSuite的问题，请稳步到该项目的[Issue]中进行讨论。

[Demo]:
<https://github.com/Tencent/TencentKonaSMSuite/tree/master/kona-ssl/src/test/java/com/tencent/kona/ssl/demo>

[SSLContext]:
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/javax/net/ssl/SSLContext.html

[Issue]:
<https://github.com/Tencent/TencentKonaSMSuite/issues>

**Comment by johnshajiang** [comment]
@shenxuebing 
关于这个问题，我在TencentKonaSMSuite开了一个新的[issue]，后续请关注它的进展，也可以直接在那里进行讨论。

[issue]:
<https://github.com/Tencent/TencentKonaSMSuite/issues/328>
