### ISSUE TITLE
Is there a clear support time for kona 11?

### ISSUE THREAD

**Issue by Bryce-huang** [Tencent/TencentKona-11#5]
I did not find a description of the support time

**Comment by shiyuexw** [comment]
Currently, we keep releasing a new release every three months. Next release is the end of June.
Each release includes the sync up with upstream, and specific modifications in Tencent Kona JDK.
We also plan to reduce the time to synchronize with the upstream.

**Comment by Bryce-huang** [comment]
Does it support JFR?
