### ISSUE TITLE
Ambiguous file name

### ISSUE THREAD

**Issue by larrylu0426** [Tencent/TencentKona-11#7]
I downloaded the release version of kona11.0.11 but I found the name of  it with the tail named ‘.b1’. However, it’s a version of ‘GA’. Should we rename it?

**Comment by shiyuexw** [comment]
For Tencent Kona JDK11，we release GA（General availability）version by default. So we remove ga from binary name. Meanwhile, use b${buildNumber} to distinguish different versions with 11.0.11.

**Comment by larrylu0426** [comment]
Got it, thanks a lot for your reply : )
