### ISSUE TITLE
软件开源-配套文档的问题

### ISSUE THREAD

**Issue by duansheli** [Tencent/TencentKona-11#8]
## 感觉配套文档 有待完善

在 #2 中提到了 参数 -XX:+FreeHeapPhysicalMemory  -XX:PeriodicGCInterval=x

分别在 jdk 8 、jdk 11 的仓库搜了下 `PeriodicGCInterval`  `FreeHeapPhysicalMemory` 
只在jdk 8 的wiki 看到一句 `物理内存释放优化（-XX:+FreeHeapPhysicalMemory开启）` 

又看了下阿里的 jdk 文档 
https://github.com/alibaba/dragonwell11/wiki/阿里巴巴Dragonwell11用户指南 
寥寥数语的几行 

## 建议 
配套文档详细点，尤其是相较于其他 jdk 的独到之处 
软件开分支，肯定是原软件某些功能没有，或较弱，自己写来的方便 
不过功能做出来，文档跟不上，别人难上手，容易劝退

**Comment by wattsun110** [comment]
@duansheli 好，谢谢反馈，这个功能目前只有kona jdk8里面有，我们这两天把这个功能相关文档更新到kona 8的wiki里面。
