### ISSUE TITLE
开启调试模式的时候，监听的ip不对

### ISSUE THREAD

**Issue by hanlukk** [Tencent/TencentKona-11#9]
用kona 11的时候
java启动参数带上-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9400

linux查看监听端口， 监听的ip是127.0.0.1, 这样子就不能远程调试
tcp        0      0 127.0.0.1:9400          0.0.0.0:*               LISTEN      9170/java

正确应该监听0.0.0.0才对

我用的kona版本是
openjdk version "11.0.11-ga" 2021-06-15
OpenJDK Runtime Environment TencentKonaJDK (build 11.0.11-ga+1)
OpenJDK 64-Bit Server VM TencentKonaJDK (build 11.0.11-ga+1, mixed mode)

**Comment by shiyuexw** [comment]
这是JDK11 和JDK8的区别。
使用JDK8:
tcp        0      0 0.0.0.0:9400            0.0.0.0:*               LISTEN      27967/java
使用JDK11:
tcp        0      0 127.0.0.1:9400          0.0.0.0:*               LISTEN      27827/java

**Comment by hanlukk** [comment]
> 这是JDK11 和JDK8的区别。
> 使用JDK8:
> tcp 0 0 0.0.0.0:9400 0.0.0.0:* LISTEN 27967/java
> 使用JDK11:
> tcp 0 0 127.0.0.1:9400 0.0.0.0:* LISTEN 27827/java
> 
> 在JDK11 上可以使用
> -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9400

感谢，已经用你的这个方法解决
